application: ps3btc
version: 5
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /static/powered-by-twitter-sig.gif
  static_files: static/powered-by-twitter-sig.gif
  upload: static/powered-by-twitter-sig.gif

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: .*
  script: ps3btc.py

